backend:
  name: github
  repo: AustinMRobinson/100daysblog

media_folder: src/images/
public_folder: src/images/

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog/
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: "thumbnail", label: "Post Thumbnail", widget: image }
      - { name: body, label: Body, widget: markdown }