backend:
  name: github
  repo: AustinMRobinson/100daysblog

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog/"
    create: true
    fields:
      - { label: Template Key, name: templateKey, widget: hidden, default: blog-post }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: thumbnail, label: Post Thumbnail, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Homepage"
        name: "index"
        create: true
        fields: 
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page" }
          - { name: title", label: Title, widget: string }
          - { name: metaimage, label: Meta Image, widget: image }
          - { name: heading, label: Heading, widget: string }
          - { name: subheading, label: Subheading, widget: string }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        create: true
        fields: 
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { name: title", label: Title, widget: string }
          - { name: metaimage, label: Meta Image, widget: image }
          - { name: heading, label: Heading, widget: string }
          - { name: subheading, label: Subheading, widget: string }
          - { name: bioimage, label: Bio Image, widget: image }
          - { name: bio, label: Bio, widget: markdown }
          - { name: location, label: Location, widget: string }